# Generated by Django 5.0.6 on 2024-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetailApp', '0002_answers_assessmentareas_awards_class_school_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('year', models.DateField(max_length=5)),
                ('StudentID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('YearLevel', models.IntegerField()),
                ('Class', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('Answers', models.CharField(max_length=5)),
                ('CorrectAnswers', models.CharField(max_length=5)),
                ('QuestionNumber', models.IntegerField()),
                ('SubjectContents', models.CharField(max_length=50)),
                ('AssessmentAreas', models.CharField(max_length=50)),
                ('sydney_correct_count_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sydney_average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sydney_participants', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_total_assessed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_area_assessed_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_area_assessed_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('participant', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_percentile', models.IntegerField()),
                ('sydney_percentile', models.IntegerField()),
                ('strength_status', models.CharField(max_length=5)),
                ('high_distinct_count', models.IntegerField()),
                ('distinct_count', models.IntegerField()),
                ('credit_count', models.IntegerField()),
                ('participant_count', models.IntegerField()),
                ('award', models.CharField(max_length=50)),
            ],
        ),
    ]
